# Generated by Django 5.1.1 on 2024-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_humidity_weather_wind_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='daily_max_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='daily_min_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
