# Generated by Django 5.1.1 on 2024-10-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_daily_max_temp_weather_daily_min_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='daily_max_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='daily_max_wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='daily_min_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='daily_min_wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
